"""add error_message to processing_jobs

Revision ID: 74ce6021c443
Revises: 31e210ddc932
Create Date: 2025-11-01 20:25:14.354791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74ce6021c443'
down_revision: Union[str, None] = '31e210ddc932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookmarks_lists_user_id', table_name='bookmarks_lists')
    op.create_index(op.f('ix_bookmarks_lists_user_id'), 'bookmarks_lists', ['user_id'], unique=False)
    op.drop_index('idx_job_progress_job_created', table_name='job_progress_events')
    op.create_index('idx_job_progress_job_created', 'job_progress_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_progress_events_job_id'), 'job_progress_events', ['job_id'], unique=False)
    op.add_column('processing_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_tags_name_lower', table_name='tags')
    op.drop_index('idx_tags_user_name_lower', table_name='tags')
    op.drop_constraint('uq_tags_name_user_id', 'tags', type_='unique')
    op.alter_column('video_tags', 'video_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('video_tags', 'tag_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('video_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_video_tags_tag_id', table_name='video_tags')
    op.drop_index('idx_video_tags_video_id', table_name='video_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_video_tags_video_id', 'video_tags', ['video_id'], unique=False)
    op.create_index('idx_video_tags_tag_id', 'video_tags', ['tag_id'], unique=False)
    op.alter_column('video_tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_tags', 'tag_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('video_tags', 'video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('uq_tags_name_user_id', 'tags', ['name', 'user_id'])
    op.create_index('idx_tags_user_name_lower', 'tags', ['user_id', sa.text('lower(name::text)')], unique=True)
    op.create_index('idx_tags_name_lower', 'tags', [sa.text('lower(name::text)')], unique=False)
    op.alter_column('tags', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('processing_jobs', 'error_message')
    op.drop_index(op.f('ix_job_progress_events_job_id'), table_name='job_progress_events')
    op.drop_index('idx_job_progress_job_created', table_name='job_progress_events')
    op.create_index('idx_job_progress_job_created', 'job_progress_events', ['job_id', sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_bookmarks_lists_user_id'), table_name='bookmarks_lists')
    op.create_index('idx_bookmarks_lists_user_id', 'bookmarks_lists', ['user_id'], unique=False)
    # ### end Alembic commands ###
